use_frameworks! :linkage => :static



platform :ios, '11.0'

target 'XCAssetsIssueDemo_Example' do
  pod 'XCAssetsIssueDemo', :path => '../'

#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  # use_frameworks!
#  # This one using `resource_bundles` with xcassets
#  pod 'TestLibrary', :git => 'https://github.com/dreampiggy/CocoaPodsTestLibrary.git'
#  # This one using `resources` with xcassets
#  pod 'TestLibrary2', :git => 'https://github.com/dreampiggy/CocoaPodsTestLibrary2.git'
  
  
  target 'XCAssetsIssueDemo_Tests' do
    inherit! :search_paths

    
  end
end
